In [ ]:
%pip install numpy

In [1]:
import numpy as np

In [3]:
x = np.array([3,1,2])
print(x)
type(x)

[3 1 2]


numpy.ndarray

In [10]:
a = [1,2,2,3,4,3,4,3,1]
u_a, indexs, counts = np.unique(a, return_index=True, return_counts = True)
print(u_a)
print(indexs)
print(counts)

[1 2 3 4]
[0 1 3 4]
[2 2 3 2]


In [13]:
def add(a=1, b=1):
    return a,b,a+b
a,b,sum = add(2,3)
print(a,b,sum)   # a가 a로 들어가고 b가 b로 들어가고 a+b가 sum으로 들어감, 순서는 상관없음.

2 3 5


In [14]:
# 정렬
# sorted 처럼
# ndarray.sprt 

In [23]:
a = np.array([1,4,2,3])
b = np.sort(a)    # a[np.argsort(a)]
print(f"a {a}")
print(f"b {b}")
c = np.argsort(a)   # 중요하니까 잊어버리지 말기기
print(f"c {c}")   # 0 2 3 1 이라고 나오는 순번을 잘 봐라라
print(f"cc {a[c]}")
a.sort()
print(f"a {a}")


a [1 4 2 3]
b [1 2 3 4]
c [0 2 3 1]
cc [1 2 3 4]
a [1 2 3 4]


In [24]:
a = np.array([1,4,2,3])
b = np.sort(a)
print(f"a{a}")
print(f"b {b}")
c = np.argsort(a)
print(f"c {c}")   
print(f"cc {a[c]}")
a.sort()
print(f"a {a}")


a[1 4 2 3]
b [1 2 3 4]
c [0 2 3 1]
cc [1 2 3 4]
a [1 2 3 4]


In [37]:
# 그 밖에 유용한 함스
a = np.array([1,4,2,3])


In [ ]:
np.mean(a)  # 평균값

In [28]:
np.std(a)  # 표준편차

1.118033988749895

In [29]:
np.var(a)  # 분산

1.25

In [30]:
np.max(a)  # 최댓값

4

In [31]:
np.min(a)  # 최솟값

1

In [34]:
np.sum(a)  # 함

10

In [35]:
np.prod(a)  # 곱

24

In [39]:
a = np.sort(x, axis=0)
print(a)

[1 2 3]


In [46]:
# a = np.sort(x, axis = 1)
# print(a)

In [44]:
# 실습. Numpy 모듈 사용해보기 2
# [1,1,2,3,4,5,5,5,5,8,9,10,11,24,100]
# 위와 같은 데이터가 있을때
# 1. 중복을 제거한 배열 출력
# 2. 1의 결과의 최대, 최소, 평균값 출력
# 3. 1의 결과의 모든 합 출력
# 4. 중복을 제거하지 않은 배열의 중간값 출력


In [48]:
b = [1,1,2,3,4,5,5,5,5,8,9,10,11,24,100]
u_b = np. unique(b)  # 유니크가 중복제거거
print(u_b)
print(np.max(u_b))
print(np.min(u_b))
print(np.mean(u_b))
print(np.sum(u_b))
print(np.median(b))

[  1   2   3   4   5   8   9  10  11  24 100]
100
1
16.09090909090909
177
5.0


In [49]:
# 실습. Numpy 모듈 사용해보기3
# x = np.arange(15, dtype=np.int64).reshape(3, 5)
# x[1:, ::2] = -99
# 위와 같은 데이터가 있을 때
# 1. 1열의 최대, 최소, 평균값 출력
# 2. 2행의 모든 합 출력
# 3. argsort 이용하여 axis=1 기준으로 오름차순, 내림차순 정렬

# 갑자기 수정함. 밑에 있는걸로 풀기

In [50]:
# 실습. Numpy 모듈 사용해보기3
# x = np.arange(15, dtype=np.int64).reshape(3, 5)
# x[1:, ::2] = -99
# 위와 같은 데이터가 있을 때
# 1. 1열의 최대, 최소, 평균값 출력
# 2. 2행의 모든 합 출력
# 3. 실습 2번 1차원 배열을 argsort 이용하여 내림차순 정렬

In [60]:
import numpy as np

# 데이터 정의
b = [1, 1, 2, 3, 4, 5, 5, 5, 5, 8, 9, 10, 11, 24, 100]

# 1. 중복 제거
u_b = np.unique(b)
print("중복 제거된 배열:", u_b)

# 2. 내림차순 정렬
sorted_indices = np.argsort(u_b)[::-1]  # 내림차순 정렬된 인덱스
sorted_u_b = u_b[sorted_indices]
print("내림차순 정렬된 배열:", sorted_u_b)


중복 제거된 배열: [  1   2   3   4   5   8   9  10  11  24 100]
내림차순 정렬된 배열: [100  24  11  10   9   8   5   4   3   2   1]


In [63]:
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [65]:
x[1,1]

6

In [67]:
x[-1,-1]

14

In [69]:
x[:,0]

array([ 0,  5, 10], dtype=int64)

In [71]:
x[1,:]

array([5, 6, 7, 8, 9], dtype=int64)

In [74]:
x[:2,:2]

array([[0, 1],
       [5, 6]], dtype=int64)

In [76]:
x[-2:,-2:]

array([[ 8,  9],
       [13, 14]], dtype=int64)

In [79]:
print(np.max(x, axis=0)[0])
print(np.min(x, axis=0)[0])
print(np.mean(x, axis=0)[0])

10
0
5.0


In [81]:
print(np.sum(x, axis=1)[2])

60


In [1]:
# arg_x = np.argsort(data)
# print(data[arg_x])